- apps/examples/cxxtest/cxxtest_main.cxx
- apps/examples/cxxtest/jsdosa.h
- framework/include/media/DataSource.hpp
- framework/include/media/InputDataSource.hpp
- framework/include/media/MediaPlayer.hpp
- framework/include/media/MediaRecorder.hpp
- framework/include/media/OutputDataSource.hpp
- framework/src/media/DataSource.cxx
- framework/src/media/Make.defs
- framework/src/media/MediaPlayer.cxx
- framework/src/media/MediaRecorder.cxx
- framework/src/media/OutputDataSource.cxx
This commit is a mediaframework c ++ prototype
> Add c++ feature for media framework

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
play_state_t -> player_state_t
play_reuslt_t -> player_result_t
> Rename play_state_t, play_result_t

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/cxxtest_main.cxx
1. Delete resume
2. Fix build err in MediaPlayer._start()
> Fix build error in MediaFramework

- apps/examples/cxxtest/MediaPlayer.hpp
It prevents dobule declaration
> Add #include guards in MediaPlayer.hpp

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
getState returns current state
> Add getState function in MediaPlayer

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
- apps/examples/cxxtest/cxxtest_main.cxx
1. fix compile error of media player
2. add namespace Media for media recorder
3. modify example
> modify logic for mediaframework

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
Add namespace Media and fix some coding rule error
> Add namespace Media for MediaPlayer

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
this is counterpart of prepare
> Set state & Add unprepare

- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
add state and uprepare function of recorder
> add state and unprepare function of recorder

- apps/examples/cxxtest/DataSource.cxx
- apps/examples/cxxtest/DataSource.hpp
- apps/examples/cxxtest/InputDataSource.cxx
- apps/examples/cxxtest/InputDataSource.hpp
- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
- apps/examples/cxxtest/OutputDataSource.cxx
- apps/examples/cxxtest/OutputDataSource.hpp
add logic for rleated DataSource
> add logic for related DataSource

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
The caller will be blocked until prepare is done.
> Make MediaPlayer.prepare() a sync call

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
If user set prepare callback, prepare user callback will run
> Add MediaPlayer user callback

- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
1. modify prepare function (change async call to sync call)
2. change condition variable name
> modify logic for sync call of function

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
> modify create function of media player

- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
> modify create function for media recorder

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
function  | pre-state
----------------------------------
create    | None
destroy   | Idle
prepare   | Idle
unprepare | Ready, Playing, Paused
start     | Ready
pause     | Playing
stop      | Playing, Paused
> Check pre-state of MediaPlayer

- apps/examples/cxxtest/RecorderDataSource.cxx
- apps/examples/cxxtest/RecorderDataSource.hpp
add constructor for recorderdatasource
> add constructor for recorderdatasource

- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
> modify logic for sync call

- apps/examples/cxxtest/MediaPlayer.cxx
Sync function can check pre-state
before waiting for cmd queue to be emptied
> Check pre-state before waiting sync

- apps/examples/cxxtest/DataSource.cxx
- apps/examples/cxxtest/DataSource.hpp
- apps/examples/cxxtest/RecorderDataSource.cxx
- apps/examples/cxxtest/RecorderDataSource.hpp
add datapath value for constructor
> add datapath value for constructor

- apps/examples/cxxtest/MediaPlayer.cxx
- apps/examples/cxxtest/MediaPlayer.hpp
This codes should be refactoried
> MediaPlayer Workaround code

- apps/examples/cxxtest/MediaRecorder.cxx
- apps/examples/cxxtest/MediaRecorder.hpp
add logic for recording and write
> add logic for recording

- apps/examples/cxxtest/cxxtest_main.cxx
> Fix merge conflict

- framework/src/media/DataSource.cxx
- framework/src/media/Make.defs
- framework/src/media/MediaPlayer.cxx
- framework/src/media/PlayerDataSource.cxx
- framework/src/media/RecorderDataSource.cxx
do not include related datasource files
> modify Make.defs for datasource

- os/drivers/audio/alc5658.c
- os/drivers/audio/audio_null.c
- os/include/tinyara/audio/audio.h
- Fix build errors caused by "AUDIO_FU_VOLUME".
> Remove AUDIO_FU_VOLUME
